### ISSUE TITLE
Mutagenic chambers not creating chaofusions

### ISSUE THREAD

**Issue by BrennenCramer** [TACHYON-Micah/Pawnmorpher#23]
**Describe the bug**
Whenever using the chambers (both big and small) to create a 2xmergedhuman chaocreature, the chaber throws all sorts of errors

**To Reproduce**
1. Place in two chambers connected to the associated modulator.
2. Have two pawns get in without setting anything on the modulator.
3. Have the modulator fuse the two chambers.
4. Wait till the fusing chamber reaches 100%.
5. See error.

**Error Log**
Unfortunately nothing in the error log is all that helpful, just some null GUI element stuff:
```GetInspectString exception on MutagenicChamber52055:
System.NullReferenceException: Object reference not set to an instance of an object
at Pawnmorph.Building_MutagenChamber.GetInspectString () <0x00337>
at (wrapper dynamic-method) RimWorld.InspectPaneFiller.DrawInspectStringFor_Patch2 (Verse.ISelectable,UnityEngine.Rect) <0x00054>

Verse.Log:Error(String, Boolean)
RimWorld.InspectPaneFiller:DrawInspectStringFor_Patch2(ISelectable, Rect)
RimWorld.InspectPaneFiller:DoPaneContentsFor(ISelectable, Rect)
RimWorld.MainTabWindow_Inspect:DoPaneContents(Rect)
RimWorld.InspectPaneUtility:InspectPaneOnGUI(Rect, IInspectPane)
RimWorld.MainTabWindow_Inspect:DoWindowContents_Patch2(Object, Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

**Expected behavior**
When the chambers finish, a chao creature should pop out.

**Screenshots**
![image](https://user-images.githubusercontent.com/48333768/64396510-b7041e80-d012-11e9-9a19-98b29eb1c260.png)

**Additional context**
This test was done on the latest steam version.

**Comment by FxWolfxe** [comment]
If anyone can reproduce this can you check if the error at line 1 in the screenshot's log (System.InvalidOperationException) is related to this issue or it was from something else. The pasted error log doesn't seem to point to the root problem with this issue
